# Análisis exploratorio de una base de datos de películas

Usa la base de datos `./data/imdb.csv`


### 1. Importar `pandas`, `matplotlib` y `numpy`

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

### 2. Leer la base de datos del archivo csv a pandas

In [2]:
df = pd.read_csv('./data/imdb.csv')

### 3. Mostrar las  primeras y últimas filas del dataframe. Hacerlo con el valor default y pasando como argumento el número entero de filas que se deseen inspeccionar.

In [3]:
df.head()
df.tail()
df.head(3)
df.tail(3)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

### 4. Continúa inspeccionando el archivo viendo todas las columnas del dataframe

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

### 5. Imprime los primeros valores de la variable `Rank`

In [5]:
df.Rank.head()

0    1
1    2
2    3
3    4
4    5
Name: Rank, dtype: int64

### 6. Demuestra que es mejor tener nombres de columnas sin espacios (notación corchetes y notación punto-variable).

### 7. Renombra las columnas que tengan espacios

In [6]:
df.rename(columns={
    "Runtime (Minutes)": "Runtime_Minutes",
    "Revenue (Millions)": "Revenue_Millions"}, inplace=True)

### 8. Utiliza tus nuevas columnas sin espacios :)

In [7]:
df.Runtime_Minutes.mean()

113.172

### 9. Visualiza la info de todo tu dataframe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              1000 non-null   int64
 1   Title             1000 non-null   object
 2   Genre             1000 non-null   object
 3   Description       1000 non-null   object
 4   Director          1000 non-null   object
 5   Actors            1000 non-null   object
 6   Year              1000 non-null   int64
 7   Runtime_Minutes   1000 non-null   int64
 8   Rating            1000 non-null   float64
 9   Votes             1000 non-null   int64
 10  Revenue_Millions  872 non-null    float64
 11  Metascore         936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

### 10. Inspecciona si hay columnas que tengan valores `NA`

In [9]:
df.isna().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime_Minutes       0
Rating                0
Votes                 0
Revenue_Millions    128
Metascore            64
dtype: int64

### 11. Imprime el número total de valores NA que haya en cada columna. Hazlo primero para la columna `Metascore` y después utiliza un ciclo for para hacerlo para todas las columnas

In [11]:
df.Metascore.isna().sum()
for col in df.columns:
    print(col, df[col].isna().sum())

Rank 0
Title 0
Genre 0
Description 0
Director 0
Actors 0
Year 0
Runtime_Minutes 0
Rating 0
Votes 0
Revenue_Millions 128
Metascore 64

### 12. Usa la magia de `dropna()`

In [12]:
df.dropna(inplace=True)

### 13. Vuelve a ver la info del dataset

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              838 non-null    int64
 1   Title             838 non-null    object
 2   Genre             838 non-null    object
 3   Description       838 non-null    object
 4   Director          838 non-null    object
 5   Actors            838 non-null    object
 6   Year              838 non-null    int64
 7   Runtime_Minutes   838 non-null    int64
 8   Rating            838 non-null    float64
 9   Votes             838 non-null    int64
 10  Revenue_Millions  838 non-null    float64
 11  Metascore         838 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 85.1+ KB

### 14. Genera estadísticos descriptivos con el método `describe()`

In [14]:
df.describe()

,Rank,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
count,838.000000,838.00000,838.000000,838.000000,8.380000e+02,838.000000,838.000000
mean,485.247017,2012.50716,114.638425,6.814320,1.932303e+05,84.564558,59.575179
std,286.572065,3.17236,18.470922,0.877754,1.930990e+05,104.520227,16.952416
min,1.000000,2006.00000,66.000000,1.900000,1.780000e+02,0.000000,11.000000
25%,238.250000,2010.00000,101.000000,6.300000,6.127650e+04,13.967500,47.000000
50%,475.500000,2013.00000,112.000000,6.900000,1.368795e+05,48.150000,60.000000
75%,729.750000,2015.00000,124.000000,7.500000,2.710830e+05,116.800000,72.000000
max,1000.000000,2016.00000,187.000000,9.000000,1.791916e+06,936.630000,100.000000

### 15. Crea un histograma de la variable Metascore. Utiliza 10 cubetas

In [15]:
plt.hist(df['Metascore'], bins=10)

NameError: name 'plt' is not defined

### 16. Crea un histograma de la variable Rating. Utiliza 10 cubetas

In [16]:
plt.hist(df['Rating'], bins=10)

NameError: name 'plt' is not defined

### 17. Vuelve a describir el dataframe y observa la media de la variable `Ratings`

In [17]:
df.describe()

,Rank,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
count,838.000000,838.00000,838.000000,838.000000,8.380000e+02,838.000000,838.000000
mean,485.247017,2012.50716,114.638425,6.814320,1.932303e+05,84.564558,59.575179
std,286.572065,3.17236,18.470922,0.877754,1.930990e+05,104.520227,16.952416
min,1.000000,2006.00000,66.000000,1.900000,1.780000e+02,0.000000,11.000000
25%,238.250000,2010.00000,101.000000,6.300000,6.127650e+04,13.967500,47.000000
50%,475.500000,2013.00000,112.000000,6.900000,1.368795e+05,48.150000,60.000000
75%,729.750000,2015.00000,124.000000,7.500000,2.710830e+05,116.800000,72.000000
max,1000.000000,2016.00000,187.000000,9.000000,1.791916e+06,936.630000,100.000000

### 18. Calcula este promedio con Numpy y después con un método de Pandas

In [18]:
np.mean(df.Rating)
df.Rating.mean()

6.814319809069212

### 19. Obten los valores únicos de la variable Rating y después ordénalos de menor a mayor

In [19]:
np.sort(df['Rating'].unique())

array([1.9, 2.7, 3.9, 4. , 4.1, 4.3, 4.4, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.8, 9. ])

### 20. Observa los ratings que te interesen y ahora filtra el dataframe con ese rating para ver cuáles son las películas con dicho rating

In [20]:
df[df.Rating == 9.0]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0

### 21. Obten los valores únicos de la variable Rating y la frecuencia total de cada uno de estos valores. Posteriormente crea un nuevo dataframe con essos valores

In [21]:
counts = df.Rating.value_counts()
counts_df = pd.DataFrame({'rating' : counts.index, 'frequency' : counts.values})

### 22. Ordena el nuevo dataframe por la variable `rating`

In [22]:
counts_df.sort_values(['rating'])

    rating  frequency
46     1.9          1
47     2.7          1
40     3.9          2
45     4.0          1
42     4.1          1
35     4.3          3
48     4.4          1
38     4.6          2
37     4.7          3
49     4.8          1
30     4.9          6
43     5.0          1
34     5.1          5
31     5.2          6
29     5.3          8
27     5.4         10
26     5.5         11
25     5.6         13
23     5.7         16
19     5.8         21
24     5.9         15
21     6.0         20
18     6.1         22
9      6.2         33
7      6.3         36
12     6.4         30
8      6.5         35
6      6.6         37
1      6.7         42
10     6.8         33
17     6.9         23
0      7.0         43
2      7.1         40
4      7.2         38
5      7.3         37
13     7.4         29
11     7.5         33
14     7.6         26
15     7.7         25
3      7.8         38
20     7.9         20
22     8.0         19
16     8.1         24
28     8.2          9
33     8.3          5
39     8.4          2
32     8.5          6
36     8.6          3
41     8.8          1
44     9.0          1

### 23. Crea una gráfica de barras con este nuevo dataframe ordenado

In [23]:
plt.bar(counts_df.rating, counts_df.frequency)

NameError: name 'plt' is not defined

### 24. Crea la matriz de correlación del dataframe de películas

In [24]:
df_corr = df[['Year', 'Runtime_Minutes', 'Rating', 'Votes', 'Revenue_Millions', 'Metascore']].corr()
df_corr

,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
Year,1.000000,-0.101933,-0.145703,-0.362445,-0.129198,-0.062303
Runtime_Minutes,-0.101933,1.000000,0.374566,0.399298,0.281721,0.221397
Rating,-0.145703,0.374566,1.000000,0.517452,0.217106,0.672731
Votes,-0.362445,0.399298,0.517452,1.000000,0.636833,0.332674
Revenue_Millions,-0.129198,0.281721,0.217106,0.636833,1.000000,0.142397
Metascore,-0.062303,0.221397,0.672731,0.332674,0.142397,1.000000

### 25. Grafica la matriz de correlación utilizando `matshow()`

In [25]:
plt.matshow(df_corr)
plt.show()

NameError: name 'plt' is not defined